### ISSUE TITLE
i love this i said that wake my world stopped working 

### ISSUE THREAD

**Issue by 372405** [EAGLECRAFTARCHIVE/EagleCraft-Download#13]
yyyyyyyy

**Comment by EAGLECRAFTARCHIVE** [comment]
Sorry i haven't been active in this page for a year now but ill try to fix any issues with the script

**Comment by 372405** [comment]
thank you for responding to me and thank you for making this project and can you please add multiplayer
________________________________
From: EAGLECRAFTARCHIVE ***@***.***>
Sent: Wednesday, March 6, 2024 9:04 PM
To: EAGLECRAFTARCHIVE/EagleCraft-Download ***@***.***>
Cc: DANIEL WADSWORTH ***@***.***>; Author ***@***.***>
Subject: [ External ]Re: [EAGLECRAFTARCHIVE/EagleCraft-Download] I hate this (Issue #13)




CAUTION: This email originated from outside of Erie's Public Schools. Do not click on links or open any attachments until you have confirmed with the sender and know the content is safe. Never reply to an outside message with any personal information including your password or phone number. Do not send money or gift cards.

Sorry i haven't been active in this page for a year now but ill try to fix any issues with the script

**Comment by 372405** [comment]
i use your the protect all the time
________________________________
From: EAGLECRAFTARCHIVE ***@***.***>
Sent: Wednesday, March 6, 2024 9:04 PM
To: EAGLECRAFTARCHIVE/EagleCraft-Download ***@***.***>
Cc: DANIEL WADSWORTH ***@***.***>; Author ***@***.***>
Subject: [ External ]Re: [EAGLECRAFTARCHIVE/EagleCraft-Download] I hate this (Issue #13)




CAUTION: This email originated from outside of Erie's Public Schools. Do not click on links or open any attachments until you have confirmed with the sender and know the content is safe. Never reply to an outside message with any personal information including your password or phone number. Do not send money or gift cards.

Sorry i haven't been active in this page for a year now but ill try to fix any issues with the script

**Comment by 372405** [comment]
g

**Comment by 372405** [comment]
hi pleses respond on monday
________________________________
From: EAGLECRAFTARCHIVE ***@***.***>
Sent: Wednesday, March 6, 2024 9:04 PM
To: EAGLECRAFTARCHIVE/EagleCraft-Download ***@***.***>
Cc: DANIEL WADSWORTH ***@***.***>; Author ***@***.***>
Subject: [ External ]Re: [EAGLECRAFTARCHIVE/EagleCraft-Download] I hate this (Issue #13)




CAUTION: This email originated from outside of Erie's Public Schools. Do not click on links or open any attachments until you have confirmed with the sender and know the content is safe. Never reply to an outside message with any personal information including your password or phone number. Do not send money or gift cards.

Sorry i haven't been active in this page for a year now but ill try to fix any issues with the script
